### ISSUE TITLE
[JOYEUSE] Redmi Note 9 Pro (Xiaomi.eu) - only black screen after flashing

### ISSUE THREAD

**Issue by skellum12** [reiryuki/Miui-Core-Magisk-Module#15]
Whenever I try to flash MIUI Core magisk it only boots up in black screen. At first it asked me to uninstall the com.miui.rom and other apps when I was flashing it on Magisk. Is it really to necessary to uninstall those system apps?  Am I missing something or im flashing the wrong version of MIUI Core?

**Comment by reiryuki** [comment]
why not read the requirements?
