### ISSUE TITLE
Android 8.1 Not Supported

### ISSUE THREAD

**Issue by iamr0s** [reiryuki/Miui-Core-Magisk-Module#16]
# Android 8.1 Not Supported
because the Android 8.1 only support dex_038 or min.
when I use MIUI-Core, It awalys show "java.io.IOException: Failed to open dex files ** because: Unrecognized version number in **: 0 3 9 "

**Comment by reiryuki** [comment]
-------------- Any missing stuffs --------------
------------- will not be approved -------------

Bug report contains 5 stuffs:

1) Explainations ✓
2) Magisk install log if it's a Magisk module #magisk_install_log
3) Disable any other else modules (except AML, dirac misoundfx Remover, AOSP soundfx Remover, & Sound Alive FX Remover Magisk Module)
4) Full logcat #logcat
5) Z folder #zscript

If you miss one of them, read #bug_report again please. If you got boot-loop, read #workarounds! If you don't understand, learning is the best you can do. Thank you.
