### ISSUE TITLE
[Dipper]The Miui-Home can't work on MI 8 which flashed the Crdroid 9.4

### ISSUE THREAD

**Issue by tdtd-cpu** [reiryuki/Miui-Core-Magisk-Module#21]
Hi,Author I have an IMPORTANT thing to tell you ,that is when I flashed the miui-home module on mi 8 which flashed the crdroid 9.4, it will stuck on the second boot screen and it can't enter the system.Would you fix the problem?

**Comment by reiryuki** [comment]
Support & Bug Report
https://t.me/androidryukimodsdiscussions/2618
If you don't do above, issues will be closed immediately
