### ISSUE TITLE
Camera failed 

### ISSUE THREAD

**Issue by XuehaoWang1** [reiryuki/Miui-Core-Magisk-Module#31]
My device is a Galaxy S23U, and after installing MIUIcore, the default camera cannot be turned on. Removing MIUIcore works fine.

![Screenshot_20240224_142449_Camera](https://github.com/reiryuki/Miui-Core-Magisk-Module/assets/118093264/c49ec6e6-f0e3-4a62-8fa9-7779c51703a2)

**Comment by reiryuki** [comment]
I will never support 'talking only' without sending proper logs. If you want a fix, then read #bug_report carefully, and send required files to the author.
