### ISSUE TITLE
Brightness bug with MIUI Core module (any ROM, Begonia)

### ISSUE THREAD

**Issue by Brewybj** [reiryuki/Miui-Core-Magisk-Module#33]
Hi, is there a fix for this brightness bug?

https://github.com/reiryuki/Miui-Core-Magisk-Module/assets/156925213/3a5dcc47-1ff0-4fac-9692-7555eb966385

**Comment by reiryuki** [comment]
I will never support 'talking only' without sending proper logs. If you want a fix, then read #bug_report carefully, and send required files to the author.
