### ISSUE TITLE
POCO_Launcher_2.20.1.42 module?

### ISSUE THREAD

**Issue by rammmma** [reiryuki/Miui-Core-Magisk-Module#5]
Can you make POCO_Launcher_2.20.1.42 or 2.20.1.40 module. Some said that this last versions with miui recent apps.
AOSP/LOS recent apps very uncomfortable. Grid not working on android 10+.
![miuiRECENT](https://user-images.githubusercontent.com/95990880/147642918-25a1065a-818f-4383-b64e-8bf8dd7fe64c.jpg)
Thank you

**Comment by reiryuki** [comment]
Please open a request at the Pull requests tab
