### ISSUE TITLE
[TUCANA] Mi Note 10 Pro - Boot freeze on MIUI screen

### ISSUE THREAD

**Issue by mchiappinam** [reiryuki/Miui-Core-Magisk-Module#6]
Hi, I'm trying to install the module on my Android 11 - Mi note 10 pro (Tucana) so then I can install ANXCamera, but I'm getting stuck on the "MIUI" booting screen. (before installing ANXCamera)

Do you know what can I do to debug/fix it?

**Comment by reiryuki** [comment]
what rom using?

**Comment by mchiappinam** [comment]
![Screenshot_2022-01-17-20-25-42-290_com android settings](https://user-images.githubusercontent.com/5289376/149854969-c707870e-c46b-4107-8eb9-612c12b395f4.jpg)

**Comment by reiryuki** [comment]
this is not for miui rom
read requirements

**Comment by mchiappinam** [comment]
It's confusing, but I'm using the original ROM for Xiaomi Mi Note 10 Pro (not redmi) (tucana). Please see attached screenshots.

![Screenshot_2022-01-25-00-47-25-520_com grarak kerneladiutor](https://user-images.githubusercontent.com/5289376/150918622-c917f2ad-ca3f-4c1f-b4cc-c69cb7f92329.jpg)
![Screenshot_2022-01-25-00-47-09-005_com grarak kerneladiutor](https://user-images.githubusercontent.com/5289376/150918626-ffab553e-f132-40f7-bb35-284f586f799e.jpg)

**Comment by reiryuki** [comment]
this module is not for miui rom
