### ISSUE TITLE
Stock MIUI Camera

### ISSUE THREAD

**Issue by kero3009destiny** [reiryuki/Miui-Core-Magisk-Module#7]
I am on Arrow 12 for polaris, should I even try ripping the original camera app from MIUI and installing it along with this magisk module or is it not worth the effort? I just want to be able to use telephoto and have better photo quality that ANXCamera did not provide.

**Comment by reiryuki** [comment]
Miui ROM doesn't need Miui Core module
and I'm not a dev of anx camera

**Comment by Applewubs** [comment]
I don't think you understood, he asked if it's possible to use MIUI stock camera on ArrowOS 12 alongside MIUI Core, he wants to use it because it has better quality than ANXCamera

And as an answer for kero question, no, it isn't possible now.

**Comment by reiryuki** [comment]
Issues tab is not for asking a question. Please use Discussions tab instead!
